# Generated by Django 4.0.8 on 2022-11-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.type'),
        ),
    ]
